  # CircleCI 2.0 configuration file
version: 2

# Re-usable blocks to reduce boilerplate in job definitions.
references:
  host_environment_defaults: &host_environment_defaults
    # Customize the JVM maximum heap limit
    JAVA_OPTS: -Xmx3200m
  docker_environment_defaults: &docker_environment_defaults
    # Customize the JVM to read correct memory values
    JAVA_OPTS: '-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1'

  default_java_job: &default_java_job
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          <<: *docker_environment_defaults
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir

  restore_source_code: &restore_source_code
    restore_cache:
      keys:
        - source-code-1.0.0-{{ .Branch }}-{{ .Revision }}
        - source-code-1.0.0-{{ .Branch }}
        - source-code-1.0.0
  restore_dependencies: &restore_dependencies
    restore_cache:
      keys:
        - sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}
        - sbt-ivy2-dependencies-1.0.0
  restore_build: &restore_build
    restore_cache:
      keys:
        - sbt-build-1.0.0-{{ .Branch }}-{{ .Revision }}
        - sbt-build-1.0.0

  setup_dependencies_key: &setup_dependencies_key
    run:
      name: Generate cache key
      command: |
        shasum build.sbt \
          project/plugins.sbt \
          project/build.properties \
          project/Dependencies.scala > /tmp/dependencies.cache.tmp

jobs:
  checkout_code:
    <<: *default_java_job
    steps:
      - *restore_source_code
      - checkout
      - save_cache:
          key: source-code-1.0.0-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/workdir

  sbt_dependencies:
    <<: *default_java_job
    steps:
      - *restore_source_code
      - *setup_dependencies_key
      - *restore_dependencies
      - run:
          name: Resolve dependencies
          command: |
            sbt update
      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.sbt
          key: sbt-ivy2-dependencies-1.0.0-{{ checksum "/tmp/dependencies.cache.tmp" }}

  compile:
    <<: *default_java_job
    steps:
      - *restore_source_code
      - *setup_dependencies_key
      - *restore_dependencies
      - *restore_build
      - run:
          name: Compile
          command: ./scripts/compile.sh
      - save_cache:
          paths:
            - ~/workdir/target
            - ~/workdir/project/target
            - ~/workdir/project/project
          key: sbt-build-1.0.0-{{ .Branch }}-{{ .Revision }}

  publish_binary_locally:
    machine: true
    environment:
      <<: *host_environment_defaults
    working_directory: ~/workdir
    steps:
      - *restore_source_code
      - *setup_dependencies_key
      - *restore_dependencies
      - *restore_build
      - run:
          name: Publish local docker
          command: ./scripts/publish-native-binary.sh -n codacy-plugins-test -m codacy.plugins.DockerTest -t docker
      - store_artifacts:
          path: ~/workdir/build/codacy-plugins-test-linux

workflows:
  version: 2
  test-and-publish:
    jobs:
      - checkout_code
      - sbt_dependencies:
          requires:
            - checkout_code
      - compile:
          requires:
            - sbt_dependencies
      - publish_binary_locally:
          requires:
            - compile
