version: 2.1

orbs:
  codacy: codacy/base@2.0.0
references:
  circleci_job: &circleci_job
    docker:
      - image: circleci/circleci-cli:0.1.5879
    working_directory: ~/workdir

jobs:
  pack_and_validate:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Pack orb
          command: |
            echo ""                                                  >> orbs/jobs/run.yml
            echo "environment:"                                      >> orbs/jobs/run.yml
            echo "  - CODACY_PLUGINS_TEST_VERSION: $(cat .version)"  >> orbs/jobs/run.yml
            echo "  - FILENAME: codacy-plugins-test-$(cat .version)" >> orbs/jobs/run.yml
            circleci config pack orbs > orb.yml
      - run:
          name: Validate orb
          command: circleci orb validate orb.yml
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - "orb.yml"

  publish_dev:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish orb as dev (deleted after 90 days)
          command: circleci orb publish orb.yml codacy/plugins-test@dev:$(cat .version) --token $CIRCLE_TOKEN

  publish_prod:
    <<: *circleci_job
    steps:
      - attach_workspace:
          at: ~/workdir
      - deploy:
          name: Publish final orb
          command: circleci orb publish orb.yml codacy/plugins-test@$(cat .version) --token $CIRCLE_TOKEN

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - codacy/checkout_and_version:
          write_sbt_version: true
      - pack_and_validate:
          context: CodacyCircleCI
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: populate_cache
          cmd: |
            sbt "set scalafmtUseIvy in ThisBuild := false;update"
            sbt update
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: check_fmt
          cmd: sbt "scalafmt::test;test:scalafmt::test;sbt:scalafmt::test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: compile_and_test
          cmd: sbt "compile;test:compile;test"
          requires:
            - populate_cache
      - codacy/sbt:
          name: build_native_image
          cmd: |
            ./scripts/build-native.sh -n $CIRCLE_PROJECT_REPONAME -m codacy.plugins.DockerTest -t docker $(cat .version)
            curl -T ~/workdir/$CIRCLE_PROJECT_REPONAME-linux-$(cat .version) -ucodacy-ci:$BINTRAY_API_KEY -H "X-Bintray-Package:$CIRCLE_PROJECT_REPONAME" -H "X-Bintray-Version:$(cat .version)" https://api.bintray.com/content/codacy/Binaries/$(cat .version)/$CIRCLE_PROJECT_REPONAME-linux
            curl -X POST -ucodacy-ci:$BINTRAY_API_KEY https://api.bintray.com/content/codacy/Binaries/$CIRCLE_PROJECT_REPONAME/$(cat .version)/publish
            GHR_FLAGS=""
            if [ "$CIRCLE_BRANCH" != "master" ]; then
              GHR_FLAGS+="-prerelease"
            fi
            mkdir -p /tmp/ghr-publish
            cp ~/workdir/$CIRCLE_PROJECT_REPONAME-linux-$(cat .version) /tmp/ghr-publish
            go get github.com/tcnksm/ghr
            ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME -c $CIRCLE_SHA1 $GHR_FLAGS -delete $(cat .version) /tmp/ghr-publish
          requires:
            - compile_and_test
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - build_native_image
      - publish_dev:
          context: CodacyCircleCI
          requires:
            - tag_version
            - pack_and_validate
          filters:
            branches:
              ignore:
                - master
      - publish_prod:
          context: CodacyCircleCI
          requires:
            - tag_version
            - pack_and_validate
          filters:
            branches:
              only:
                - master
