package codacy.plugins.test
import com.codacy.plugins.api.languages.{Language, Languages}

object Utils {

  val languageComments = Map[Language, Seq[String]](Languages.Javascript -> Seq("//", "/*"),
                                                    Languages.Scala -> Seq("/*", "//"),
                                                    Languages.CSS -> Seq("/*"),
                                                    Languages.LESS -> Seq("/*"),
                                                    Languages.SASS -> Seq("/*"),
                                                    Languages.PHP -> Seq("#", "//"),
                                                    Languages.C -> Seq("/*", "//"),
                                                    Languages.CPP -> Seq("/*", "//"),
                                                    Languages.ObjectiveC -> Seq("/*", "//"),
                                                    Languages.Python -> Seq("#"),
                                                    Languages.Ruby -> Seq("#"),
                                                    Languages.Kotlin -> Seq("//", "/*"),
                                                    Languages.Perl -> Seq("#"),
                                                    Languages.Java -> Seq("//", "/*"),
                                                    Languages.CSharp -> Seq("//", "/*"),
                                                    Languages.VisualBasic -> Seq("'"),
                                                    Languages.Go -> Seq("//"),
                                                    Languages.Elixir -> Seq("#"),
                                                    Languages.Clojure -> Seq("#", ";;"),
                                                    Languages.CoffeeScript -> Seq("#"),
                                                    Languages.Rust -> Seq("//"),
                                                    Languages.Swift -> Seq("//"),
                                                    Languages.Haskell -> Seq("--"),
                                                    Languages.Shell -> Seq("#"),
                                                    Languages.TypeScript -> Seq("//", "/*"),
                                                    Languages.XML -> Seq("<!--"),
                                                    Languages.Dockerfile -> Seq("#"),
                                                    Languages.PLSQL -> Seq("--", "/*"),
                                                    Languages.JSON -> Seq("//", "/*"),
                                                    Languages.Apex -> Seq("//", "/*"),
                                                    Languages.Velocity -> Seq("/*"),
                                                    Languages.JSP -> Seq("<%--"),
                                                    Languages.VisualForce -> Seq("<!--"),
                                                    Languages.R -> Seq("#"),
                                                    Languages.Powershell -> Seq("#", "<#"),
                                                    Languages.Solidity -> Seq("//", "/*"),
                                                    Languages.Markdown -> Seq("<!--"),
                                                    Languages.Crystal -> Seq("#"),
                                                    Languages.YAML -> Seq("#"))
}
